name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ['3.10', '3.11', '3.12', '3.13']
    steps:
      - name: Setup Python ${{ matrix.python_version }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python_version }}
      - name: Fetch lonelypss
        uses: actions/checkout@v7
      - name: Set up uv
        uses: astral-sh/setup-uv@v10.2.0
        with:
          enable-cache: true
      - name: Install dependencies
        run: uv sync --extra dev --extra standard
      - name: Lint lonelypss with black
        run: uv run black --check src/lonelypss
      - name: Type check lonelypss with mypy
        working-directory: src
        run: uv run mypy lonelypss --explicit-package-bases --disallow-untyped-defs
      - name: Lint lonelypss with ruff
        run: uv run ruff check --output-format=github src
